# Site settings
name: Book
email: xy15800046890@outlook.com
author: Brian
url: https://brianczy.github.io/Books/
resume_site: https://brianczy.github.io/Books/
github: https://github.com/BrianCZY/Books/
baseurl: "/Books"
description: 身体和思想总要有一个在路上
meta_description: 小洋;个人博客;天道酬勤；功不唐捐
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: brianczy

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

